# Régression linéaire et résultats

En utilisant le notebook « Nettoyage des données », nous allons effectuer une régression linéaire sur les données nettoyées.

In [45]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [ ]:
import s3fs
import pandas as pd
import tempfile
fs = s3fs.S3FileSystem(client_kwargs={"endpoint_url": "https://minio.lab.sspcloud.fr"})

MY_BUCKET = "gbern13"

FILE_PATH_S3 = f"{MY_BUCKET}/diffusion/PISA2022/student_questionnaire/CY08MSP_STU_QQQ.SAS7BDAT"
with fs.open(FILE_PATH_S3, "rb") as s3f:
    df = pd.read_sas(s3f)

print(df.head())

In [47]:
df.shape

(613744, 1278)

In [48]:
variables=['CNTSTUID','ST004D01T','ESCS','WORKPAY','WORKHOME','ICTRES','BULLIED',
'SCHRISK','FAMSUP','TEACHSUP','SCHSUST','CREATOOS','CREATAS','EXPO21ST','FEELSAFE','DISCLIM','COGACMCO']
## Réduction du dataset à ces variables 
data=df[variables].copy()
## Nouveaux noms des variables 
renom=['CNTSTUID','gender','society','work','household_care','digital_home',
'social','school_safety','family_support','teacher_support','school_support','creative_out',
'creative_at','math_reasoning','safety','climate_math','math_thinking']
## Renommage des variables
data.columns=renom
data.head()

,CNTSTUID,gender,society,work,household_care,digital_home,social,school_safety,family_support,teacher_support,school_support,creative_out,creative_at,math_reasoning,safety,climate_math,math_thinking
0,800001.0,1.0,1.1112,0.0,10.0,4.9507,-1.2280,-0.6386,1.8355,1.5558,NaN,NaN,4.1226,2.4031,1.1246,0.6387,2.4962
1,800002.0,2.0,-3.0507,NaN,NaN,-3.4930,1.3336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.1246,NaN,NaN
2,800003.0,2.0,-0.1867,0.0,0.0,0.4307,NaN,-0.6386,NaN,NaN,NaN,NaN,NaN,NaN,0.8637,-0.8615,NaN
3,800005.0,1.0,-3.2198,0.0,10.0,-2.1392,0.9885,-0.6386,-0.7468,1.5558,1.5382,1.4468,1.0191,0.3556,-0.7560,0.4426,-0.1216
4,800006.0,1.0,-1.0548,0.0,4.0,-0.5542,-1.2280,-0.6386,-0.5122,0.1475,0.2241,1.8557,1.6583,-1.0257,1.1246,0.4029,0.7927

In [ ]:
FILE_PATH_S3 = f"{MY_BUCKET}/diffusion/PISA2022/student_questionnaire/CY08MSP_STU_QQQ.SAS7BDAT"
with fs.open(FILE_PATH_S3, "rb") as s3f:
    creat_df = pd.read_sas(s3f)
creat_df = creat_df[['CNTSTUID','PV1CRTH_NC']]
creat_df.head()

   CNTSTUID  PV1CRTH_NC
0  800001.0         2.9
1  800002.0         4.6
2  800003.0         6.5
3  800005.0         0.4
4  800006.0        14.3

La matrice de corrélation dans le notebook précédent montre que les variables « creative_out » et « creative_at » sont fortement corrélées (corrélation de 0,75), de même que « digital_home » et « society ». Nous proposons de remplacer les deux premières par leur moyenne (puisque l'on s'attendait à ce qu'elles soient similaires) et, pour les deux dernières, de vérifier le VIF.

In [50]:
data['creative_total'] = (data['creative_at']+data['creative_out'])/2
data.drop(['creative_at','creative_out'],axis=1,inplace=True)

In [60]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor

X = data.drop('CNTSTUID', axis=1)

X_clean = X.dropna()

vif = pd.DataFrame()
vif['Variable'] = X_clean.columns
vif['VIF'] = [variance_inflation_factor(X_clean.values, i) for i in range(X_clean.shape[1])]

vif = vif.sort_values('VIF', ascending=False)
print(vif.to_string(index=False))

       Variable      VIF
 household_care 2.960955
         gender 2.847606
   digital_home 2.315628
        society 2.267123
           work 1.473303
  math_thinking 1.345951
         social 1.257598
teacher_support 1.250780
 creative_total 1.246411
  school_safety 1.235392
 math_reasoning 1.207040
   climate_math 1.169415
 family_support 1.162876
 school_support 1.149549
         safety 1.106986

On remarque que les deux variables « society » et « digital_home » ont un VIF faible. Même si les variables sont corrélées, elles apportent des informations différentes à la régression. Nous proposons donc de conserver les deux variables dans le modèle.

In [61]:
final_df = pd.merge(data, creat_df, on='CNTSTUID', how='inner')
final_df.shape

(499843, 17)

In [62]:
final_df.head()

,CNTSTUID,gender,society,work,household_care,digital_home,social,school_safety,family_support,teacher_support,school_support,math_reasoning,safety,climate_math,math_thinking,creative_total,PV1CRTH_NC
0,800001.0,1.0,1.1112,0.0,10.0,4.9507,-1.2280,-0.6386,1.8355,1.5558,NaN,2.4031,1.1246,0.6387,2.4962,NaN,2.9
1,800002.0,2.0,-3.0507,NaN,NaN,-3.4930,1.3336,NaN,NaN,NaN,NaN,NaN,1.1246,NaN,NaN,NaN,4.6
2,800003.0,2.0,-0.1867,0.0,0.0,0.4307,NaN,-0.6386,NaN,NaN,NaN,NaN,0.8637,-0.8615,NaN,NaN,6.5
3,800005.0,1.0,-3.2198,0.0,10.0,-2.1392,0.9885,-0.6386,-0.7468,1.5558,1.5382,0.3556,-0.7560,0.4426,-0.1216,1.23295,0.4
4,800006.0,1.0,-1.0548,0.0,4.0,-0.5542,-1.2280,-0.6386,-0.5122,0.1475,0.2241,-1.0257,1.1246,0.4029,0.7927,1.75700,14.3

Alors, on peut faire une première régression linéaire.

In [63]:
X = final_df.drop(['PV1CRTH_NC', 'CNTSTUID'], axis=1)
y = final_df['PV1CRTH_NC'] 

df_clean = pd.concat([X, y], axis=1).dropna()
X_clean = df_clean.drop('PV1CRTH_NC', axis=1)
y_clean = df_clean['PV1CRTH_NC']

X_const = sm.add_constant(X_clean)

# Ajustar o modelo
model = sm.OLS(y_clean, X_const).fit()

# Ver resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             PV1CRTH_NC   R-squared:                       0.286
Model:                            OLS   Adj. R-squared:                  0.286
Method:                 Least Squares   F-statistic:                     2701.
Date:                Sun, 28 Dec 2025   Prob (F-statistic):               0.00
Time:                        00:11:23   Log-Likelihood:            -3.8684e+05
No. Observations:              101038   AIC:                         7.737e+05
Df Residuals:                  101022   BIC:                         7.739e+05
Df Model:                          15
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              32.5155      0.131    248.596      0.000      32.259      32.772
gender             -0.7375      0.073    -10.082      0.000      -0.881      -0.594
society             2.9847      0.043     68.935      0.000       2.900       3.070
work               -0.5911      0.013    -46.660      0.000      -0.616      -0.566
household_care      0.0238      0.010      2.335      0.020       0.004       0.044
digital_home        0.9903      0.038     25.963      0.000       0.916       1.065
social             -0.3963      0.037    -10.844      0.000      -0.468      -0.325
school_safety      -1.0207      0.039    -26.208      0.000      -1.097      -0.944
family_support      0.5978      0.035     16.872      0.000       0.528       0.667
teacher_support    -0.1408      0.034     -4.089      0.000      -0.208      -0.073
school_support      1.2627      0.035     35.798      0.000       1.194       1.332
math_reasoning     -0.0365      0.037     -0.998      0.318      -0.108       0.035
safety              0.1450      0.038      3.834      0.000       0.071       0.219
climate_math        0.6597      0.039     16.704      0.000       0.582       0.737
math_thinking      -0.1105      0.038     -2.914      0.004      -0.185      -0.036
creative_total     -2.5460      0.034    -74.303      0.000      -2.613      -2.479
==============================================================================
Omnibus:                     1989.015   Durbin-Watson:                   1.827
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1200.655
Skew:                           0.112   Prob(JB):                    1.91e-261
Kurtosis:                       2.515   Cond. No.                         30.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

La variable « math_reasoning » n'est pas significative. On la supprime.

In [64]:
X = final_df.drop(['PV1CRTH_NC', 'CNTSTUID'], axis=1) 
y = final_df['PV1CRTH_NC'] 

df_clean = pd.concat([X, y], axis=1).dropna()
X_clean = df_clean.drop(['PV1CRTH_NC','math_reasoning'], axis=1)
y_clean = df_clean['PV1CRTH_NC']

X_const = sm.add_constant(X_clean)


model = sm.OLS(y_clean, X_const).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             PV1CRTH_NC   R-squared:                       0.286
Model:                            OLS   Adj. R-squared:                  0.286
Method:                 Least Squares   F-statistic:                     2894.
Date:                Sun, 28 Dec 2025   Prob (F-statistic):               0.00
Time:                        00:11:23   Log-Likelihood:            -3.8684e+05
No. Observations:              101038   AIC:                         7.737e+05
Df Residuals:                  101023   BIC:                         7.739e+05
Df Model:                          14
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              32.5077      0.131    248.983      0.000      32.252      32.764
gender             -0.7353      0.073    -10.057      0.000      -0.879      -0.592
society             2.9840      0.043     68.928      0.000       2.899       3.069
work               -0.5913      0.013    -46.680      0.000      -0.616      -0.566
household_care      0.0236      0.010      2.313      0.021       0.004       0.044
digital_home        0.9902      0.038     25.962      0.000       0.915       1.065
social             -0.3961      0.037    -10.838      0.000      -0.468      -0.324
school_safety      -1.0211      0.039    -26.218      0.000      -1.097      -0.945
family_support      0.5965      0.035     16.848      0.000       0.527       0.666
teacher_support    -0.1462      0.034     -4.301      0.000      -0.213      -0.080
school_support      1.2608      0.035     35.797      0.000       1.192       1.330
safety              0.1433      0.038      3.794      0.000       0.069       0.217
climate_math        0.6609      0.039     16.741      0.000       0.583       0.738
math_thinking      -0.1171      0.037     -3.136      0.002      -0.190      -0.044
creative_total     -2.5489      0.034    -74.671      0.000      -2.616      -2.482
==============================================================================
Omnibus:                     1988.970   Durbin-Watson:                   1.826
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1200.341
Skew:                           0.112   Prob(JB):                    2.23e-261
Kurtosis:                       2.515   Cond. No.                         30.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Quelques commentaires sur la régression :
Le fait d'être une femme diminue le score de créativité — cela peut être dû à un biais lié à une variable omise.
Les variables `society`, `digital_home`, `family_support`, `household_care`, `school_support` et `safety` ont des coefficients positifs, ce qui est logique.
La variable `work` a un coefficient négatif ; cela peut s'expliquer par le fait que, si l'on a plus de temps pour soi, on a plus de temps pour créer.
`math_thinking` a un coefficient négatif, ce qui n'est pas clair. Peut‑être qu'un raisonnement logique diminue la créativité.

Maintenant, pour un effet quadratique, on ajoute la variable digital_home^2

In [65]:
final_df['digital_home2'] = final_df['digital_home']**2

In [66]:
X = final_df.drop(['PV1CRTH_NC', 'CNTSTUID'], axis=1) 
y = final_df['PV1CRTH_NC']

df_clean = pd.concat([X, y], axis=1).dropna()
X_clean = df_clean.drop(['PV1CRTH_NC','math_reasoning'], axis=1)
y_clean = df_clean['PV1CRTH_NC']

X_const = sm.add_constant(X_clean)

model = sm.OLS(y_clean, X_const).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             PV1CRTH_NC   R-squared:                       0.292
Model:                            OLS   Adj. R-squared:                  0.292
Method:                 Least Squares   F-statistic:                     2783.
Date:                Sun, 28 Dec 2025   Prob (F-statistic):               0.00
Time:                        00:11:24   Log-Likelihood:            -3.8641e+05
No. Observations:              101038   AIC:                         7.729e+05
Df Residuals:                  101022   BIC:                         7.730e+05
Df Model:                          15
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              33.0833      0.131    251.669      0.000      32.826      33.341
gender             -0.7615      0.073    -10.460      0.000      -0.904      -0.619
society             2.7706      0.044     63.388      0.000       2.685       2.856
work               -0.5667      0.013    -44.838      0.000      -0.591      -0.542
household_care      0.0139      0.010      1.367      0.172      -0.006       0.034
digital_home        0.7841      0.039     20.304      0.000       0.708       0.860
social             -0.3697      0.036    -10.156      0.000      -0.441      -0.298
school_safety      -1.0018      0.039    -25.829      0.000      -1.078      -0.926
family_support      0.5754      0.035     16.319      0.000       0.506       0.645
teacher_support    -0.1493      0.034     -4.411      0.000      -0.216      -0.083
school_support      1.2483      0.035     35.590      0.000       1.180       1.317
safety              0.1536      0.038      4.085      0.000       0.080       0.227
climate_math        0.6654      0.039     16.928      0.000       0.588       0.742
math_thinking      -0.0984      0.037     -2.647      0.008      -0.171      -0.026
creative_total     -2.4644      0.034    -72.250      0.000      -2.531      -2.398
digital_home2      -0.3784      0.013    -29.532      0.000      -0.404      -0.353
==============================================================================
Omnibus:                     2066.477   Durbin-Watson:                   1.829
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1242.766
Skew:                           0.117   Prob(JB):                    1.37e-270
Kurtosis:                       2.509   Cond. No.                         32.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Ce tableau nous montre un gain décroissant de créativité à partir d'ajout d'accés à information. En effet, la valeur optimal serait 0.7841/(2*0.3784)=1.03.